// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.config([
  '$httpProvider', '$locationProvider', '$stateProvider', '$urlRouterProvider', '$sceDelegateProvider', function($httpProvider, $locationProvider, $stateProvider, $urlRouterProvider, $sceDelegateProvider) {
    $httpProvider.defaults.useXDomain = true;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
    $httpProvider.defaults.headers.common = {
      'Accept': 'application/hal+json'
    };
    $httpProvider.defaults.headers.post = {
      'Content-Type': 'application/json'
    };
    $locationProvider.html5Mode(true);
    $locationProvider.hashPrefix('!');
    $sceDelegateProvider.resourceUrlWhitelist(['**']);
    $stateProvider.state('friends', {
      url: '/friends',
      controller: 'FriendsController',
      templateUrl: 'components/friends/views/friends.html',
      resolve: {
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        }
      }
    }).state('user', {
      url: '/user/:userId',
      controller: 'UserController',
      templateUrl: 'components/user/views/user.html',
      resolve: {
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        },
        user: function($stateParams, LocalStorage, RestModel) {
          return RestModel.moreInfo($stateParams.userId, LocalStorage.getItem('params'));
        }
      }
    }).state('wall', {
      url: '/user/:userId/selected/:selectedId/wall',
      controller: 'WallController',
      templateUrl: 'components/wall/views/wall.html',
      resolve: {
        user: function($stateParams, LocalStorage, RestModel) {
          return RestModel.moreInfo($stateParams.userId, LocalStorage.getItem('params'));
        },
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        }
      }
    }).state('photo', {
      url: '/user/:userId/selected/:selectedId/photo',
      controller: 'PhotoController',
      templateUrl: 'components/photo/views/photo.html',
      resolve: {
        user: function($stateParams, LocalStorage, RestModel) {
          return RestModel.moreInfo($stateParams.userId, LocalStorage.getItem('params'));
        },
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        }
      }
    }).state('user-friend', {
      url: '/user/:userId/friends',
      controller: 'UserFriendsController',
      templateUrl: 'components/userFriendsList/views/userFriendList.html',
      resolve: {
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        }
      }
    }).state('selected', {
      url: '/user/:userId/selected/:type',
      controller: 'SelectedController',
      templateUrl: 'components/selected/views/selected.html',
      resolve: {
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        }
      }
    }).state('processingPhoto', {
      url: '/user/:userId/processing',
      controller: 'ProcessingPhotoController',
      templateUrl: 'components/processingPhoto/views/processing.html',
      resolve: {
        params: function(LocalStorage) {
          return LocalStorage.getItem('params');
        },
        currentUser: function(RestModel, $stateParams, params) {
          return RestModel.getUserById($stateParams.userId, params);
        },
        friends: function(RestModel, $stateParams, params) {
          return RestModel.getFriends(params, $stateParams.userId);
        }
      }
    });
    return $urlRouterProvider.otherwise('/login');
  }
]);

MainModule.run(function($rootScope, $state) {
  return $rootScope.$on('$stateChangeSuccess', function() {
    return $('body').scrollTop(0);
  });
});


