// Generated by CoffeeScript 1.7.1
'use strict';
FriendsModule.controller('FriendsController', function($scope, $location, $window, $timeout, $state, $stateParams, params, Static, Notification, ngTableParams, LocalStorage, Loader, RestModel, currentUser) {
  if (currentUser) {
    $scope.currentUser = currentUser;
  } else {
    $scope.currentUser;
  }
  $scope.openTable = false;
  $scope.loading = false;
  $scope.hideUsers = [];
  $scope.resultHide = [];
  Static.params = params;
  $scope.params = $scope.params || LocalStorage.getItem('params');
  $scope.getStat = function() {
    return $state.transitionTo('statistics', {
      userId: $scope.currentUser.id
    });
  };
  $scope.openListGroup = function() {
    return $state.transitionTo('groups');
  };
  $scope.getGlobalStat = function() {
    return $state.transitionTo('global');
  };
  $scope.getFriendsWhoHideYour = function() {
    var count, listFriends;
    count = $scope.friends.length;
    listFriends = angular.copy($scope.friends);
    listFriends = RestModel.friendsOnlineOrDelete(null, listFriends);
    $scope.loading = true;
    return Static.getHideFriendsList(count, listFriends, $scope.currentUser.id, []).then(function(result) {
      $scope.resultHide = result;
      if ($scope.resultHide.length === 0) {
        Notification.show('Скорее всего вас никто не скрывает.');
        return $scope.loading = false;
      } else {
        return Static.getFriends($scope.resultHide, []).then(function(users) {
          $scope.loading = false;
          return $scope.hideUsers = users;
        }, function(error) {
          return Notification.error(error);
        });
      }
    }, function(error) {
      return Notification.error(error);
    });
  };
  $scope.getListFriends = function() {
    $scope.hideUsers = [];
    $scope.page = 1;
    $scope.friendsOnline = [];
    $scope.openTableOnline = false;
    if (!$scope.friends) {
      $scope.loading = true;
      return RestModel.getFriends($scope.params).then(function(data) {
        $scope.countFriends = data.response.count;
        $scope.loading = false;
        $scope.friends = RestModel.isWorkingFriendsObject(data);
        return $scope.openTable = $scope.friends ? true : false;
      }, function(error) {
        return Notification.error(error);
      });
    } else {
      return $scope.openTable = true;
    }
  };
  $scope.getListFriendsOnlineOrDelete = function(type) {
    $scope.hideUsers = [];
    $scope.page = 1;
    $scope.friendsArray = RestModel.friendsOnlineOrDelete(type, $scope.friends);
    $scope.openTable = false;
    return $scope.openTableOnline = $scope.friendsArray ? true : false;
  };
  $scope.signOff = function() {
    LocalStorage.removeAllItem();
    $scope.openAccess = false;
    $scope.openTable = false;
    return $state.transitionTo('login');
  };
  $scope.more = function(user) {
    $state.transitionTo('user', {
      userId: user.id || user.uid
    });
    return LocalStorage.setItem('page', $scope.page);
  };
  if (LocalStorage.getItem('page')) {
    $scope.getListFriends();
  }
  $scope.page = LocalStorage.getItem('page') ? LocalStorage.getItem('page') : 1;
  return $scope.pageSize = 50;
});

//# sourceMappingURL=FriendsController.map
