// Generated by CoffeeScript 1.7.1
'use strict';
FriendsModule.controller('FriendsController', function($scope, $location, $window, $state, $stateParams, params, ngTableParams, LocalStorage, RestModel) {
  $scope.openAccess = true;
  $scope.openTable = false;
  $scope.params = $scope.params || LocalStorage.getItem('params');
  $scope.page = 1;
  $scope.pageSize = 7;
  RestModel.getUserById($scope.params.user_id, $scope.params).then(function(data) {
    return $scope.currentUser = data.response[0];
  }, function(error) {
    return console.log(error);
  });
  $scope.getListFriends = function() {
    $scope.friendsOnline = [];
    $scope.openTableOnline = false;
    if (!$scope.friends) {
      return RestModel.getFriends($scope.params).then(function(data) {
        console.log(data);
        $scope.countFriends = data.response.count;
        $scope.friends = RestModel.isWorkingFriendsObject(data);
        return $scope.openTable = $scope.friends ? true : false;
      }, function(error) {
        return console.log(error);
      });
    } else {
      return $scope.openTable = true;
    }
  };
  $scope.getListFriendsOnlineOrDelete = function(type) {
    console.log($scope.page);
    $scope.page = 1;
    $scope.friendsArray = RestModel.friendsOnlineOrDelete(type, $scope.friends);
    $scope.openTable = false;
    return $scope.openTableOnline = $scope.friendsArray ? true : false;
  };
  $scope.signOff = function() {
    LocalStorage.removeAllItem();
    $scope.openAccess = false;
    $scope.openTable = false;
    return $window.location = '/login';
  };
  return $scope.more = function(user) {
    LocalStorage.setItem('last', user.last_seen);
    return $state.transitionTo('user', {
      userId: user.id
    });
  };
});

//# sourceMappingURL=FriendsController.map
