// Generated by CoffeeScript 1.7.1
'use strict';
UserModule.controller('UserController', function($scope, $stateParams, $location, $state, RestModel, Notification, LocalStorage, user, params) {
  $scope.window = window;
  $scope.params = params;
  $scope.user = RestModel.isWorkingFriendsObject(user);
  $scope.lastSeen = LocalStorage.getItem('last');
  $scope.back = function() {
    return $scope.window.history.back();
  };
  $scope.home = function() {
    return $state.transitionTo('friends');
  };
  $scope.checkWall = function(user) {
    return $state.transitionTo('selected', {
      userId: user.id,
      type: 'wall'
    });
  };
  $scope.getUserFriends = function(user) {
    return $state.transitionTo('user-friend', {
      userId: user.id
    });
  };
  $scope.checkPhoto = function(user) {
    return $state.transitionTo('selected', {
      userId: user.id,
      type: 'photo'
    });
  };
  return console.log($scope.openAccess);
});

//# sourceMappingURL=UserController.map
