// Generated by CoffeeScript 1.7.1
'use strict';
MigrationsModule.controller('GlobalStatController', function($scope, $stateParams, $state, RestModel, params, $timeout) {
  $scope.menu = [
    {
      title: 'Родной город',
      description: 'Cтатистика по пользователям, проживающим в городах',
      url: 'migrations'
    }, {
      title: 'Отношения Вконтакте',
      description: 'Статистика по полу и отношениям',
      url: 'relations'
    }
  ];
  $scope.goToStat = function(state) {
    $state.transitionTo(state);
    return $scope.loading = true;
  };
  return $scope.home = function() {
    return $state.transitionTo('friends');
  };
});

//# sourceMappingURL=GlobalStatController.map
