// Generated by CoffeeScript 1.7.1
'use strict';
MigrationsModule.controller('MigrationsController', function($scope, $stateParams, $state, RestModel, params, Notification) {
  $scope.params = params;
  $scope.searching = false;
  $scope.home = function() {
    return $state.transitionTo('friends');
  };
  $scope.global = function() {
    return $state.transitionTo('global');
  };
  $scope.hometown = '';
  $scope.resUsers = [];
  $scope.resUserInMoskow = [];
  $scope.resUserInPiter = [];
  $scope.searchCountUsers = function() {
    $scope.searching = true;
    return RestModel.getUsersHomeTown($scope.hometown, '', $scope.params).then(function(data) {
      $scope.popularUsers = data.response.items;
      $scope.resUsers = [];
      $scope.resUsers.push({
        town: $scope.hometown,
        count: data.response.count
      });
      return RestModel.getUsersHomeTown($scope.hometown, 1, $scope.params).then(function(data) {
        $scope.resUserInMoskow = [];
        if ($scope.hometown !== "Москва") {
          $scope.resUserInMoskow.push({
            text: 'Переехали в Москву',
            count: data.response.count
          });
        } else {
          $scope.resUserInMoskow.push({
            text: 'Живут в Москве',
            count: data.response.count
          });
        }
        return RestModel.getUsersHomeTown($scope.hometown, 2, $scope.params).then(function(data) {
          if ($scope.hometown !== "Санкт-Петербург") {
            $scope.resUserInPiter = [];
            return $scope.resUserInPiter.push({
              text: 'Переехали в Санкт-Петербург',
              count: data.response.count
            });
          } else {
            return $scope.resUserInPiter.push({
              text: 'Живут в Санкт-Петербурге',
              count: data.response.count
            });
          }
        });
      }, function(error) {
        return Notification.error(error);
      });
    }, function(error) {
      return Notification.error(error);
    });
  };
  return $scope.refresh = function() {
    return $scope.searching = false;
  };
});

//# sourceMappingURL=MigrationsController.map
