// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.controller('MainController', function($scope, $location, $http, $timeout, RestModel, LocalStorage, Notification) {
  $scope.openAccess = false;
  $scope.content = {};
  $scope.linkPage = ['main', 'project', 'wishes'];
  $scope.select = $scope.linkPage[0];
  $scope.url = RestModel.getLinkAutorization();
  if (window.location.href.indexOf("access_token") !== -1) {
    $scope.openAccess = true;
    $scope.params = RestModel.getParams(window.location.href);
    LocalStorage.setItem('params', $scope.params);
    window.location.hash = '';
    window.location.href = 'http://vkopen.16mb.com/friends';
  } else {
    if (LocalStorage.getItem('params')) {
      $scope.openAccess = true;
      if (window.location.pathname === '/login' || window.location.pathname === '/') {
        $location.path('/friends');
      }
    } else {
      $scope.error = "error";
    }
  }
  $scope.selectMain = function() {
    console.log(1);
    return $scope.select = $scope.linkPage[0];
  };
  $scope.selectProject = function() {
    console.log(2);
    return $scope.select = $scope.linkPage[1];
  };
  $scope.selectWishes = function() {
    console.log(3);
    return $scope.select = $scope.linkPage[2];
  };
  return $scope.sendWish = function() {
    var reg;
    reg = /^[\w\.\d-_]+@[\w\.\d-_]+\.\w{2,4}$/i;
    if (!angular.isDefined($scope.content.email) || !angular.isDefined($scope.content.wish) || $scope.content.wish === '' || $scope.content.email === '') {
      Notification.show('Не заполенено обязательное поле!');
      return true;
    } else if (!reg.test($scope.content.email)) {
      Notification.show('Неккоректный email');
      return true;
    } else {
      return RestModel.getWish($scope.content).then(function(data) {
        Notification.show("Спасибо за отзыв");
        $scope.content = {};
        return $timeout(function() {
          return $location.path('/login');
        }, 2000);
      });
    }
  };
});

//# sourceMappingURL=MainController.map
