// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.directive('animate', function($timeout) {
  return {
    scope: {
      count: '='
    },
    link: function(scope, element) {
      console.log(scope);
      return $timeout(function() {
        $.Tween.propHooks.number = {
          get: function(tween) {
            var num;
            num = tween.elem.innerHTML.replace(/^[^\d-]+/, '');
            return parseFloat(num) || 0;
          },
          set: function(tween) {
            var opts;
            opts = tween.options;
            return tween.elem.innerHTML = (opts.prefix || '') + tween.now.toFixed(opts.fixed || 0) + (opts.postfix || '');
          }
        };
        return element.delay(2000).animate({
          number: scope.count
        }, {
          duration: 5000
        });
      });
    }
  };
});

//# sourceMappingURL=CountAnimateDirective.map
