// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.directive('image', function($http, $compile) {
  return {
    link: function(scope, element) {
      var template;
      if (scope.openBigBlade) {
        template = '/directives/views/image.html';
        return $http.get(template).success(function(data) {
          var image;
          image = $compile(data)(scope);
          return element.append(image);
        });
      }
    }
  };
});

//# sourceMappingURL=ImageDirective.map
