// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.directive('move', function($http, $timeout) {
  return {
    link: function(scope, element) {
      scope.backInResult = function() {
        $timeout(function() {
          return $('html,body').animate({
            scrollTop: scope.offcet
          }, 500);
        });
        scope.lookedItems = false;
        return scope.onlyCurrent = true;
      };
      scope.showPrev = function() {
        $timeout(function() {
          return $('.prev').click();
        });
        scope.onlyCurrent = true;
        return true;
      };
      scope.showNext = function() {
        $timeout(function() {
          return $('.next').click();
        });
        scope.onlyCurrent = true;
        return true;
      };
      return $timeout(function() {
        if ($(window).scrollTop() >= "250") {
          $("#ToTop").fadeIn("slow");
        }
        $(window).scroll(function() {
          if ($(window).scrollTop() <= "250") {
            return $("#ToTop").fadeOut("slow");
          } else {
            return $("#ToTop").fadeIn("slow");
          }
        });
        if ($(window).scrollTop() <= $(document).height() - "999") {
          $("#OnBottom").fadeIn("slow");
        }
        $(window).scroll(function() {
          if ($(window).scrollTop() >= $(document).height() - "999") {
            return $("#OnBottom").fadeOut("slow");
          } else {
            return $("#OnBottom").fadeIn("slow");
          }
        });
        $("#ToTop").click(function() {
          return $("html,body").animate({
            scrollTop: 0
          }, "slow");
        });
        $("#OnBottom").click(function() {
          return $("html,body").animate({
            scrollTop: $(document).height()
          }, "slow");
        });
        return $("#OnBottom").click(function() {
          return $("html,body").animate({
            scrollTop: $(document).height()
          }, "slow");
        });
      });
    }
  };
});

//# sourceMappingURL=MoveDirective.map
