// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.directive('slide', function($timeout) {
  return {
    link: function(scope, element) {
      return $timeout(function() {
        return $(".rslides").responsiveSlides({
          auto: false,
          speed: 500,
          nav: true,
          prevText: "Назад",
          nextText: "Далее",
          maxwidth: 500
        });
      });
    }
  };
});

//# sourceMappingURL=SliderDirective.map
