// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.directive('tabs', function($timeout) {
  return {
    link: function(scope, element) {
      return $timeout(function() {
        return element.easyResponsiveTabs();
      });
    }
  };
});

//# sourceMappingURL=TabsDirective.map
