// Generated by CoffeeScript 1.7.1
'use strict';
var StatisticsFriendsModule;

StatisticsFriendsModule = angular.module("StatisticsFriendsModule", []);

//# sourceMappingURL=StatisticsFriendsModule.map
