// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.constant('familyStatus', {
  notMarried: 'Не женат (не замужем)',
  meeting: 'Встречается',
  engaged: 'Помолвлен (а)',
  married: 'Женат (замужем)',
  complicated: 'Все сложно',
  active: 'В активном поиске',
  loved: 'Влюблен (а)'
});

MainModule.constant('sex', {
  man: 'Мужсокй пол',
  woman: 'Женский пол'
});

//# sourceMappingURL=Constants.map
