// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.constant('familyStatus', {
  not: 'Нет семейного положения',
  notMarried: 'Не женат (не замужем)',
  meeting: 'Встречается',
  engaged: 'Помолвлен (а)',
  married: 'Женат (замужем)',
  complicated: 'Все сложно',
  active: 'В активном поиске',
  loved: 'Влюблен (а)',
  hide: 'Скрытое семейное положение'
});

MainModule.constant('sex', {
  man: 'Мужсокй пол',
  woman: 'Женский пол'
});

MainModule.constant('posts', {
  yes: 'Можно написать на стене',
  no: 'Нельзя написать на стене'
});

MainModule.constant('messages', {
  yes: 'Можно написать в личку',
  no: 'Нельзя написать в личку'
});

MainModule.constant('universities', {
  yes: 'Учились в университите',
  no: 'Не учились в университете'
});

//# sourceMappingURL=Constants.map
