// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.service('LocalStorage', function($window) {
  var LocalStorage, storage;
  LocalStorage = (function() {
    LocalStorage.storage = null;

    function LocalStorage(type) {
      this.storage = $window[type];
    }

    LocalStorage.prototype.setItem = function(name, item) {
      if (angular.isObject(item) || angular.isArray(item)) {
        item = angular.toJson(item);
      }
      return this.storage.setItem(name, item);
    };

    LocalStorage.prototype.getItem = function(name, item) {
      var e;
      item = this.storage.getItem(name);
      try {
        item = angular.fromJson(item);
      } catch (_error) {
        e = _error;
        console.log(e);
      }
      return item;
    };

    LocalStorage.prototype.removeItem = function(item) {
      return this.storage.removeItem(item);
    };

    LocalStorage.prototype.removeAllItem = function() {
      return this.storage.clear();
    };

    return LocalStorage;

  })();
  storage = new LocalStorage('localStorage');
  return storage;
});

//# sourceMappingURL=LocalStorageModel.map
