// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.service('Notification', function($rootScope, $q, ngToast) {
  var Notification;
  return new (Notification = (function() {
    function Notification() {}

    Notification.prototype.success = function(message) {
      return ngToast.success({
        content: message,
        timeout: 3000
      });
    };

    Notification.prototype.error = function(message) {
      return ngToast.danger({
        content: message,
        timeout: 3000
      });
    };

    Notification.prototype.show = function(message) {
      return ngToast.info({
        content: message,
        timeout: 3000
      });
    };

    return Notification;

  })());
});

//# sourceMappingURL=NotificationService.map
