// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.service('Notification', function($rootScope) {
  var Notification;
  return new (Notification = (function() {
    function Notification() {}

    Notification.prototype.show = function(message) {
      return $rootScope.$broadcast('message:show', {
        type: 'notification',
        message: message
      });
    };

    return Notification;

  })());
});

//# sourceMappingURL=NotificationService.map
