// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.factory('UserModel', function() {
  var UserModel;
  UserModel = (function() {
    function UserModel() {}

    return UserModel;

  })();
  return {
    relationStatus: {
      0: {
        id: 0,
        name: '0'
      },
      1: {
        id: 1,
        name: '1'
      },
      2: {
        id: 2,
        name: '2'
      },
      3: {
        id: 3,
        name: '3'
      },
      4: {
        id: 4,
        name: 'замужем за'
      }
    }
  };
});

//# sourceMappingURL=UserModel.map
