// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.factory('UserModel', function() {
  var UserModel;
  return UserModel = (function() {
    function UserModel() {}

    UserModel.prototype.model = 'users';

    UserModel.relationStatus = {
      0: {
        id: 0,
        name: '-'
      },
      1: {
        id: 1,
        male: 'свободный парень',
        female: 'свободная девушка'
      },
      2: {
        id: 2,
        name: 'дружит с ',
        other: 'с кем то гуляет..'
      },
      3: {
        id: 3,
        male: 'помолвлен',
        female: 'помолвлена',
        maleOther: 'помолвлен с ',
        femaleOther: 'помолвлена с '
      },
      4: {
        id: 4,
        male: 'есть жена - ',
        female: 'есть муж -',
        maleOther: 'женат',
        femaleOther: 'замужем'
      },
      5: {
        id: 5,
        name: 'все непонятно',
        other: 'все непонятно c '
      },
      6: {
        id: 6,
        name: 'активно ищет пару'
      },
      7: {
        id: 7,
        male: 'влюблен',
        female: 'влюблена',
        maleOther: 'влюблен в ',
        femaleOther: 'влюблена в '
      }
    };

    UserModel.getRelationStatus = function(user) {
      var relationStatus;
      if (user.relation) {
        if (user.relation_partner) {
          if (user.sex === 1) {
            switch (user.relation) {
              case 2:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 3:
                relationStatus = UserModel.relationStatus[user.relation].femaleOther;
                break;
              case 4:
                relationStatus = UserModel.relationStatus[user.relation].female;
                break;
              case 5:
                relationStatus = UserModel.relationStatus[user.relation].other;
                break;
              case 7:
                relationStatus = UserModel.relationStatus[user.relation].femaleOther;
            }
          } else {
            switch (user.relation) {
              case 2:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 3:
                relationStatus = UserModel.relationStatus[user.relation].maleOther;
                break;
              case 4:
                relationStatus = UserModel.relationStatus[user.relation].male;
                break;
              case 5:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 7:
                relationStatus = UserModel.relationStatus[user.relation].maleOther;
            }
          }
        } else {
          if (user.sex === 1) {
            switch (user.relation) {
              case 1:
                relationStatus = UserModel.relationStatus[user.relation].female;
                break;
              case 2:
                relationStatus = UserModel.relationStatus[user.relation].other;
                break;
              case 3:
                relationStatus = UserModel.relationStatus[user.relation].female;
                break;
              case 4:
                relationStatus = UserModel.relationStatus[user.relation].femaleOther;
                break;
              case 5:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 6:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 7:
                relationStatus = UserModel.relationStatus[user.relation].female;
            }
          } else {
            switch (user.relation) {
              case 1:
                relationStatus = UserModel.relationStatus[user.relation].male;
                break;
              case 2:
                relationStatus = UserModel.relationStatus[user.relation].other;
                break;
              case 3:
                relationStatus = UserModel.relationStatus[user.relation].male;
                break;
              case 4:
                relationStatus = UserModel.relationStatus[user.relation].maleOther;
                break;
              case 5:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 6:
                relationStatus = UserModel.relationStatus[user.relation].name;
                break;
              case 7:
                relationStatus = UserModel.relationStatus[user.relation].male;
            }
          }
        }
      } else {
        relationStatus = null;
      }
      return relationStatus;
    };

    return UserModel;

  })();
});

//# sourceMappingURL=UserModel.map
