// Generated by CoffeeScript 1.7.1
'use strict';
UserFriendsModule.controller('UserFriendsController', function($scope, $location, $stateParams, RestModel, LocalStorage, params) {
  $scope.stateParams = $stateParams;
  $scope.window = window;
  $scope.params = params;
  $scope.page = 1;
  $scope.pageSize = 10;
  $scope.userId = $scope.stateParams.userId;
  $scope.back = function() {
    return $scope.window.history.back();
  };
  $scope.home = function() {
    return $location.path('/friends');
  };
  $scope.userFriendsArray = null;
  RestModel.getUserById($scope.userId, $scope.params).then(function(data) {
    return $scope.currentUser = data.response[0];
  }, function(error) {
    return console.log(error);
  });
  RestModel.getFriends(params, $scope.userId).then(function(data) {
    $scope.countFriends = data.response.count;
    return $scope.userFriends = RestModel.isWorkingFriendsObject(data);
  }, function(error) {
    return console.log(error);
  });
  $scope.getListFriendsOnlineOrDelete = function(type) {
    return $scope.userFriendsArray = RestModel.friendsOnlineOrDelete(type, $scope.userFriends);
  };
  $scope.getListFriends = function() {
    return $scope.userFriendsArray = null;
  };
  return $scope.more = function(user) {
    return LocalStorage.setItem('last', user.last_seen);
  };
});

//# sourceMappingURL=UserFriendsController.map
